on:
  issue_comment:
    types: created

jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    if: ${{ (!github.event.issue.pull_request) && (github.event.issue.labels[0].name == 'messaging room') }}
    steps:
      - uses: checkout@v3
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          mkdir chatrooms
          cd chatrooms
          echo ${MSGSENDER}: ${MSGBODY}>>${ROOMTITLE}.txt
          git add -A
          git commit -m 'user message'
          git push
        env:
          MSGBODY: ${{ github.event.comment.body }}
          ROOMTITLE: ${{ github.event.issue.title }}
          MSGSENDER: ${{ github.event.comment.user.name }}
