on:
  issue_comment:
    types: created

jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    if: ${{ (!github.event.issue.pull_request) && (github.event.issue.labels[0].name == 'messaging room') }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name "${ACTOR}"
          git config --global user.email "${ACTOR}@users.noreply.github.com"
          cd chatrooms
          echo ${MSGSENDER}: ${MSGBODY}>>${ROOMTITLE}.txt
          git add .
          git commit -m 'user message'
          git push origin HEAD:main
        env:
          MSGBODY: ${{ github.event.comment.body }}
          ROOMTITLE: ${{ github.event.issue.title }}
          MSGSENDER: ${{ github.event.comment.user.login }}
          ACTOR: ${{ github.actor }}
