on:
  issue_comment:
    types: created

jobs:
  issue_commented:
    name: Issue comment
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request }}
    steps:
      - run: |
          echo $(MSGBODY)>>chatrooms/$().txt
        env:
          MSGBODY: ${{ github.event.comment.body }}
          ROOMTITLE: ${{ github.event.issue.title }}
